function cfg = default_seg_debug()
    cfg = struct( ...
        "enable", false, ...
        "class", "all", ...
        "imageName", "", ...
        "detIndex", [], ...
        "showTiltFrame", true ...
        );
end
