function R = quat_xyzw_to_rotm(qxyzw)
    qxyzw = reshape(double(qxyzw), [1 4]);
    x = qxyzw(1); y = qxyzw(2); z = qxyzw(3); w = qxyzw(4);
    R = [ ...
        1 - 2*(y*y + z*z), 2*(x*y - z*w),     2*(x*z + y*w); ...
        2*(x*y + z*w),     1 - 2*(x*x + z*z), 2*(y*z - x*w); ...
        2*(x*z - y*w),     2*(y*z + x*w),     1 - 2*(x*x + y*y) ...
        ];
end
