function info = default_color_info()
    info = struct( ...
        "label", "", ...
        "score", NaN, ...
        "source", "", ...
        "meanHSV", [NaN NaN NaN], ...
        "meanRGB", [NaN NaN NaN], ...
        "pixelCount", 0, ...
        "points", NaN, ...
        "targetBin", "" ...
        );
end
