function cfg = default_color_config()
    cfg = struct( ...
        "cubeShrink", 0.82, ...
        "cubeErodeRadius", 2, ...
        "cylErodeRadius", 2, ...
        "cylBodyMajorPct", 68, ...
        "bboxInsetFrac", 0.12, ...
        "minPixels", 40, ...
        "minCompArea", 40, ...
        "hueSigma", 0.060, ...
        "satWeightPow", 1.4, ...
        "minVal", 0.08, ...
        "maxVal", 1.00, ...
        "minSatCube", 0.10, ...
        "minSatCylinder", 0.16, ...
        "cubePurpleHueMin", 0.645, ...
        "cubePurpleHueMax", 0.740, ...
        "cubePurpleMinSat", 0.14, ...
        "cubePurpleMaxVal", 0.62, ...
        "uprightBottleRingFrac", 0.58, ...
        "uprightBottleMinSideScore", 0.22, ...
        "uprightBottleBlueOverrideMargin", 0.18 ...
        );
end
